# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/deployment.json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: token
  labels:
    app: token
spec:
  selector:
    matchLabels:
      app: token
  template:
    metadata:
      labels:
        app: token
    spec:
      containers:
        - name: token
          image: mirzaahilmi/token:1.0.0
          ports:
            - name: token
              containerPort: 1026
          volumeMounts:
            - mountPath: /run
              name: token
              readOnly: true
          env:
            - name: CONFIG_FILE
              value: /run/.secret.json
      volumes:
        - name: token
          secret:
            secretName: token
